# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('activation_key', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Activation key')),
                ('date_key_expiration', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date key expiration')),
                ('companies', models.ManyToManyField(blank=True, related_name='users_all', to='core.Company', verbose_name='Companies')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_active', to='core.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['user'],
            },
        ),
    ]
