# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborator',
            name='roles',
            field=models.ManyToManyField(blank=True, to='core.Role', verbose_name='Roles'),
        ),
    ]
