# Generated by Django 2.0 on 2017-12-25 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('account', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(blank=True, through='account.Colaborator', to='core.Company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_active', to='core.Company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.Company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='notification',
            name='contenttype',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='users_all', to='core.Company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='Permissions'),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='profile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='roles',
            field=models.ManyToManyField(blank=True, to='core.Role', verbose_name='Roles'),
        ),
        migrations.AlterUniqueTogether(
            name='colaborator',
            unique_together={('profile', 'company')},
        ),
    ]
