# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('account', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(blank=True, through='account.Colaborator', to='core.Company', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_active', to='core.Company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='users_all', to='core.Company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='Permissions'),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='profile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='roles',
            field=models.ManyToManyField(blank=True, to='core.Role', verbose_name='Roles'),
        ),
        migrations.AlterUniqueTogether(
            name='colaborator',
            unique_together=set([('profile', 'company')]),
        ),
    ]
