# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0002_auto_20171124_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Active')),
                ('object_id', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Object ID')),
                ('date_read', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Read date')),
                ('level', models.SlugField(blank=True, editable=False, null=True, verbose_name='Level')),
                ('content', models.CharField(editable=False, max_length=250, verbose_name='Content')),
                ('destination', models.URLField(editable=False, verbose_name='Destination')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.Company', verbose_name='Company')),
                ('contenttype', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
