# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170726_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nav_expanded',
            field=models.BooleanField(default=True, verbose_name='Nav expanded'),
        ),
    ]
