# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='account/profiles/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='account/profiles/thumb/', verbose_name='Photo thumb'),
        ),
    ]
