#!/bin/bash
NAME="matrix"
DJANGODIR=/var/www/matrix.cubo.pe/htdocs
SOCKFILE=/var/www/matrix.cubo.pe/run/gunicorn.sock
LOGFILE=/var/www/matrix.cubo.pe/logs/gunicorn.log
USER=root
GROUP=root
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=matrix.settings
DJANGO_WSGI_MODULE=matrix.wsgi

echo "Starting $NAME as `whoami`"

cd $DJANGODIR
source env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

exec env/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
