# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_domain',
            field=models.URLField(blank=True, null=True, verbose_name='Custom domain'),
        ),
    ]
