# Generated by Django 2.0.6 on 2018-06-02 01:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Active')),
                ('object_id', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Object ID')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Start date')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Finish date')),
                ('notify', models.CharField(default=0, max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Notify')),
                ('notified', models.CharField(blank=True, editable=False, max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Notified')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('type', models.SlugField(choices=[('appointment', 'Appointment'), ('call', 'Call'), ('job-start', 'Job start'), ('private', 'Private'), ('task', 'Task')], verbose_name='Type')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Active')),
                ('token', models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='Token')),
                ('destination', models.URLField(verbose_name='Destination')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Active')),
                ('object_id', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Object ID')),
                ('date_fail', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fail date')),
                ('date_read', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Read date')),
                ('date_send', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Send date')),
                ('direction', models.SlugField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', editable=False, verbose_name='Direction')),
                ('token', models.CharField(blank=True, max_length=150, null=True, verbose_name='Token')),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='From email')),
                ('from_name', models.CharField(blank=True, max_length=50, verbose_name='From name')),
                ('to_email', models.TextField(blank=True, verbose_name='To email')),
                ('to_email_cc', models.TextField(blank=True, verbose_name='To email CC')),
                ('to_email_bcc', models.TextField(blank=True, verbose_name='To email BCC')),
                ('reply_to_email', models.TextField(blank=True, verbose_name='Reply to email')),
                ('subject', models.CharField(max_length=150, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_creation'],
                'permissions': (('send_message', 'Can send message'),),
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='Active')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('link', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='common.Link', verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ['date_creation'],
            },
        ),
    ]
