# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20171124_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contenttype',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Object ID'),
        ),
    ]
